### ISSUE TITLE
Add endpoint that allows for more than one MUC room to be created with one request.

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-restAPI-plugin#127]
The pre-existing endpoint `POST /restapi/v1/chatrooms` can be used to create one new MUC room.

For certain applications, it is desirable to create many chatrooms at once. The REST API plugin should have a new endpoint that is suitable for this. The API could be very similar to the existing, single-room endpoint, but should take a collection of rooms as it's input parameter.

I'm unsure if we can overload `POST /restapi/v1/chatrooms` with an alternative that takes a collection of chat room elements. If that can be done without breaking backwards compatibility with the pre-existing variant that crates one room, that might be preferred. If that's not possible, we might need to use a different address for the endpoint.

**Comment by evdherberg** [comment]
Overloading is going to be, at least, hard. So for the moment I will go for `POST /restapi/v1/chatrooms/bulk`.

Question though: do we want this to have an all-or-nothing character, so if creation of one room fails no rooms are created at all? Or is 'best effort', i.e. create whatever can be created, good enough?

**Comment by guusdk** [comment]
Can we easily make that configurable/an option?

**Comment by evdherberg** [comment]
All-or-nothing is a lot more effort, because (for as far as I know) creating a room is not a transactional thing. So we would need to implement some rollback functionality. And to do that properly, we would need to store the state of those rooms from before this action. Messy. So if we do that, then it is just a small extra effort to make it optional. The complexity will be 99% in the transactional behaviour.

The fastest solution is to go best effort. And then, possibly, respond back to the client which rooms have been created, and which haven't, and for what reason.

**Comment by guusdk** [comment]
That makes sense. Let's go with the fastest solution then, returning an error message that lists entities that could not be created.
